//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservacionEventosUSAM.Models.CRUD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReservacionEventos2021Entities : DbContext
    {
        public ReservacionEventos2021Entities()
            : base("name=ReservacionEventos2021Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<local_evento> local_evento { get; set; }
        public virtual DbSet<modulos> modulos { get; set; }
        public virtual DbSet<operaciones> operaciones { get; set; }
        public virtual DbSet<persona_eventos> persona_eventos { get; set; }
        public virtual DbSet<registro_inscripcion> registro_inscripcion { get; set; }
        public virtual DbSet<reservacion_evento> reservacion_evento { get; set; }
        public virtual DbSet<rol_opera> rol_opera { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tipo_evento> tipo_evento { get; set; }
        public virtual DbSet<tipo_persona> tipo_persona { get; set; }
        public virtual DbSet<userState> userState { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
    }
}
