//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservacionEventosUSAM.Models.CRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class registro_inscripcion
    {
        public int id_inscripcion { get; set; }
        public int id_reservacion { get; set; }
        public string nombres_persona { get; set; }
        public string apellidos_persona { get; set; }
        public string telefono_persona { get; set; }
        public string correo_persona { get; set; }
        public int id_tipo_persona { get; set; }
    
        public virtual reservacion_evento reservacion_evento { get; set; }
        public virtual tipo_persona tipo_persona { get; set; }
    }
}
