//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroEventosUSAM.Models.CRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public int id_usuario { get; set; }
        public string usuario { get; set; }
        public string contrasena_usuario { get; set; }
        public int cod_estado { get; set; }
        public int id_rol { get; set; }
    
        public virtual roles roles { get; set; }
        public virtual userState userState { get; set; }
    }
}
