//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroEventosUSAM.Models.CRUDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class persona_eventos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public persona_eventos()
        {
            this.reservacion_evento = new HashSet<reservacion_evento>();
        }
    
        public int id_persona { get; set; }
        public string nombres_persona { get; set; }
        public string apellidos_persona { get; set; }
        public string profesion_persona { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservacion_evento> reservacion_evento { get; set; }
    }
}
